import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import LoginModal from '@/components/modals/LoginModal'
import RegisterModal from '@/components/modals/RegisterModal'
import Layout from '@/components/LayoutContext'

import { Toaster } from 'react-hot-toast';
import AuthContext from '@/context/AuthContext'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Kann Nicht',
  description: 'Generated by me',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          <Toaster />
            <RegisterModal/>
            <LoginModal/>
            <Layout>
              {children}
            </Layout>
        </AuthContext>
      </body>
    </html>
  )
}
